version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "pr/no-changelog"
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "pr/no-changelog"
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    # Until there is capacity to review UI updates, disable PRs so they won't block other updates
    # (default of five pull requests for version updates).
    open-pull-requests-limit: 0
    labels:
      - "dependencies"
      - "pr/no-changelog"
  - package-ecosystem: "gomod"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "pr/no-changelog"
  # Keep the release branch up to date with patch updates.
  - target-branch: "release/2.0.x"
    package-ecosystem: "gomod"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
    ignore:
    - dependency-name: "*"
      update-types:
      - "version-update:semver-major"
      - "version-update:semver-minor"
    labels:
      - "dependencies"
      - "pr/no-changelog"
