name: OSV-Scanner Scheduled Scan

on:
  schedule:
    - cron: "30 12 * * 1"
  # Allow manual triggering
  workflow_dispatch:

permissions:
  # Required to upload SARIF file.
  actions: read
  # Require writing security events to upload SARIF file to security tab.
  security-events: write
  # Only need to read contents.
  contents: read

jobs:
  osv-scan-scheduled:
    strategy:
      matrix:
        branches:
          - main
          - release/2.0.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: "Run scanner"
        uses: google/osv-scanner-action/osv-scanner-action@c411404a6c37528d821d2851028dd3856bebe8b9 # v1.9.1
        with:
          scan-args: |-
            --output=results.json
            --format=json
            --recursive
        continue-on-error: true
      - name: "Run osv-scanner-reporter"
        uses: google/osv-scanner-action/osv-reporter-action@c411404a6c37528d821d2851028dd3856bebe8b9 # v1.9.1
        with:
          scan-args: |-
            --output=${{ inputs.results-file-name }}
            --new=results.json
            --gh-annotations=false
      - name: "Upload SARIF file"
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
      - name: "Error troubleshooter"
        if: ${{ always() && steps.upload_artifact.outcome == 'failure' }}
        run: |
          echo "::error::Artifact upload failed. This is most likely caused by a error during scanning earlier in the workflow."
          exit 1
